import { VerticalBox } from "std-widgets.slint";
import {Board} from "./board.slint";
import {FlatUi, View, CurrentView, ScreenSize, SlintPlayer, SlintPosition, SlintPlayerSide, SlintSquare} from "./structs.slint";
import {Theme} from "./config.slint";
import {PlayerBox} from "./player.slint";
import {Game} from "./game.slint";
import {Lobby} from "./lobby.slint";


export component AppWindow inherits Window {
    width: s_width * 1px;
    height: s_height * 1px;
    title: "Checkers";
    background: Theme.background;   

    in property <FlatUi> ui_hints;
    in property <ScreenSize> screen_size;
    in-out property <View> view;
    
    property <int> s_width: screen_size.screen_width * 0.85;
    property <int> s_height: screen_size.screen_height * 0.85;
    property <int> board_size: Math.min(self.s_width, self.s_height);
    property <int> player_width: (s_width - board_size) / 2;
    property <int> piece_size: (player_width / 2) * 0.75;
    

    property <bool> is_red: ui_hints.turn == SlintPlayerSide.Red;
    callback player_move(SlintPosition);
    callback start_game();
    callback quit();
    callback to_lobby();
    
    if view.current_view == CurrentView.Lobby: Lobby {
      start_game => {start_game();} 
      quit => {quit();}
    }
  
    if view.current_view == CurrentView.Game: Game {
      board_size: board_size;
      player_width: player_width;
      p_width: parent.width;
      p_height: parent.height;
      piece_size: piece_size;
      ui_hints: ui_hints;
      player_move(pos) => {player_move(pos);}
      quit() => {quit();}
      to_lobby() => {to_lobby();}
    } 
 
    

}
