import { VerticalBox } from "std-widgets.slint";
import {Board} from "./board.slint";
import {FlatUi, ScreenSize, SlintPlayer, SlintPosition, SlintPlayerSide, SlintSquare} from "./structs.slint";
import {Theme} from "./config.slint";
import {PlayerBox} from "./player.slint";

export component AppWindow inherits Window {
    width: s_width * 1px;
    height: s_height * 1px;
    title: "Checkers";
    background: Theme.background;

    in property <FlatUi> ui_hints;
    in property <ScreenSize> screen_size;
    
    property <int> s_width: screen_size.screen_width * 0.85;
    property <int> s_height: screen_size.screen_height * 0.85;
    property <int> board_size: Math.min(self.s_width, self.s_height);
    property <int> player_width: (s_width - board_size) / 2;
    property <int> piece_size: (player_width / 2) * 0.75;
    

    property <bool> is_red: ui_hints.turn == SlintPlayerSide.Red;
    callback player_move(SlintPosition);
    HorizontalLayout {
        width: parent.width;
        height: parent.height;
        horizontal-stretch: 1;
                
        PlayerBox {
          ui_hints: root.ui_hints; 
          side: SlintPlayerSide.Red;
          horizontal-stretch: 1;
          min-width: player_width * 1px;
          piece_size: piece_size;
          
        }

        Board {
          height: board_size * 1px;
          width: board_size * 1px;
          ui_hints: root.ui_hints; 
          player_move(pos) => {root.player_move(pos);}
        }
        
        PlayerBox {
          ui_hints: root.ui_hints; 
          side: SlintPlayerSide.Black;
          horizontal-stretch: 1;
          min-width: player_width * 1px;
          piece_size: piece_size;
        }
    }
 
    

}
