import { VerticalBox } from "std-widgets.slint";
import { SlintPosition, FlatUi, SlintSquare, SlintPlayer, SlintPlayerSide } from "./structs.slint";
import { Theme, Images } from "./config.slint";

export component Board inherits VerticalBox {
       
      in property <FlatUi> ui-hints;

      callback player_move(SlintPosition); 
      
      padding: 0px;
      VerticalBox{
        spacing: 0px;

        Rectangle {
          border-width: Theme.border_width;
          border-radius: Theme.border_radius;
          border-color: Theme.board-border;
          clip: true;
       
          VerticalBox {
            spacing: 0px;
            padding: 0px;

            for row in 8: HorizontalLayout {
              spacing: 0px;
            
              for col in 8: Rectangle {
                
                in-out property <SlintPosition> pos: {row: row, col: col};

                property <int> index: row * 8 + col;
                property <bool> is-black: Math.mod((row + col), 2) != 0;
                property <bool> is-selectable: ui-hints.selectable[index] || ui-hints.targets[index];
                property <bool> is-selected: ui-hints.selected == index; 
                
                background: is-black ? Theme.background : Theme.text-color;
                border-width: is-selectable || zone.has-hover ? 4px : 0px;
                border-radius: is-selected || zone.has-hover || is-selected ? 4px : 0px;
                border-color: root.ui-hints.selected == index ? Theme.selected-color : Theme.selectable-color;
                
                drop-shadow-color: is-selected ? rgba(244, 184, 96, 0.6) : rgba(000, 000, 000, 0);
                drop-shadow-blur: is-selected ? 12px : 0px;

                zone := TouchArea {
                    enabled: is-selectable; 
                    width: parent.width;
                    height: parent.height;
                    clicked => { root.player_move(parent.pos);}
                }
             
                if ui-hints.board[index] != 0: Image{
                 source:
                    root.ui-hints.board[index] == 1 ? Images.red-base :
                    root.ui-hints.board[index] == 2 ? Images.red-king :
                    root.ui-hints.board[index] == 3 ? Images.black-base :
                    root.ui-hints.board[index] == 4 ? Images.black-king :
                    @image-url("");

                  width: parent.width * 0.85;
                  height: parent.height * 0.85;
                  horizontal-alignment: center;
                  vertical-alignment: center;
                }    
                    
              }
            }
          }
        }
      }
  }
