
export global Images {
  in property <image> red-base: @image-url("assets/red_piece.png");
  in property <image> red-king: @image-url("assets/red_king.png");
  in property <image> black-base: @image-url("assets/black_piece.png");
  in property <image> black-king: @image-url("assets/black_king.png"); 
}

export global Theme {
  in property <color> red: #FF0000;
  in property <color> black: #000000;
  in property <color> background: #0f172a;
  in property <color> board-border: #737373;
  in property <color> selectable-color: #FFFFFF;
  in property <color> selected-color: #00EE00;
  in property <color> hovered-color: #00FF00;
  in property <length> border_width: 3px;
  in property <length> border_radius: 12px;
  in property <color> border_color: #737373;
  }
