export enum SlintSquare {RedBase, RedKing, BlackBase, BlackKing, Empty}

export enum CurrentView {
  Lobby,
  Game,
  Winner,
  }

export struct View {
  current_view: CurrentView,
  }

export enum SlintPlayerSide {Red, Black}

export struct ScreenSize {screen_width: int, screen_height: int}

export struct SlintPlayer {
  name: string,
  side: SlintPlayerSide,
  captured: [SlintSquare],
  }

export struct FlatUi {
  board: [int],
  selected: int,
  selectable: [bool], 
  targets: [bool],
  players: [SlintPlayer],
  turn: SlintPlayerSide,
  }

export struct SlintPosition {
      row: int,
      col: int,
  }


